// import { Inter, Rubik_Burned } from 'next/font/google'
import './globals.css'

import localfont from "next/font/local"
import { StoreProvider } from '@/redux/StoreProvider';



const rub = localfont({
  src: [
    {
    path: "../../public/fonts/RubikBurned-Regular.ttf",
    weight: "400",
  },
],
  variable: "--font-rubik",
});

export const metadata = {
  title: 'SABA',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${rub.variable} font-sans`}>
      <body >
        <StoreProvider>
          {children} 
        </StoreProvider> 
      </body>
    </html>
  )
}
